language: scala
scala:
  - 2.13.1
script:
  - '! sbt compile | grep -F "[warn]"' # a hack to make sure we compile without warnings
  - '! sbt test:compile | grep -F "[warn]"' # a hack to make sure we compile without warnings
  - sbt test
  - sbt scalafmtCheck
  - sbt scalafmtSbtCheck
  - sbt "runMain org.dabr.rng4cats.examples.RefExample"
  - sbt "runMain org.dabr.rng4cats.examples.StateExample"
