language: scala
scala:
  - 2.13.1
env:
  - CI=true
script:
  - sbt compile
  - sbt test
  - sbt scalafmtCheck
  - sbt scalafmtSbtCheck
  # Run all main classes
  - sbt "show discoveredMainClasses" | grep "* " | awk '{print $3}' | xargs -I {} sbt "runMain {}"
